name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST  }}
          username: ${{ secrets.SSH_USER  }}
          key: ${{ secrets.SSH_KEY  }}
          port: 22
          debug: true
          script: |
            cd  /home1/aadilhostinfo/public_html/zatca
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
